# Generated by Django 4.1.1 on 2022-11-04 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('Classnumber', models.IntegerField(blank=True, default='0000', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='D', max_length=10, null=True)),
                ('start_time', models.TimeField(blank=True, default='0', null=True)),
                ('end_time', models.TimeField(blank=True, default='0', null=True)),
                ('dates', models.IntegerField(blank=True, default='0', null=True)),
                ('shopping', models.ManyToManyField(to='list_app.student')),
            ],
        ),
    ]
