# Generated by Django 4.1.1 on 2022-11-07 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_remove_shoppingcart_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 23, 11, 50, 809299, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='rating',
            name='thoughts',
            field=models.TextField(default=''),
        ),
    ]
