# Generated by Django 4.1.1 on 2022-11-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0005_rating_pub_date_rating_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 23, 17, 32, 647422, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
