# Generated by Django 4.1.1 on 2022-11-08 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0006_alter_rating_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='GPA',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='professor',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='whichClass',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
