# Generated by Django 4.1.1 on 2022-11-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0007_rating_gpa_rating_professor_rating_whichclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ratings',
        ),
    ]
